### PR TITLE
Persist user data in Context API and display username on /game route

### LINKED ISSUE #330: Persist User Data and Display Username on /game Route
## Overview

When a user signs in, their information is currently not being stored or shared throughout the application. This feature aims to persist the user data using the Context API and display the user's username on the `/game` route upon a successful login.

## Background

Presently, after a successful login, the user's details are not saved, leading to potential issues in features that require user data. To enhance the user experience and maintain state across components, a centralized storage using the Context API is required. Additionally, displaying the username on the `/game` route provides users with immediate feedback that they are logged in.

## Requirements

- **Persist User Data:**
  - Utilize Context API to store and manage user information across the application.
  - Ensure the context is available in all necessary components.

- **Display Username on /game Route:**
  - Extract the user's username from the stored data and display it prominently on the `/game` route.

- **Error Handling:**
  - Implement proper error handling for failed login attempts.
  - Provide clear feedback to the user in case of login issues.

## Technical Considerations

- Ensure that the Context API integration does not introduce unnecessary re-renders that might affect performance.
- Manage state changes cleanly to avoid data leaks or inconsistencies.
- Keep consistent styling with the rest of the application (refer to [DeWordle README](https://github.com/Lead-Studios/DeWordle?tab=readme-ov-file) for guidelines).
- **Environment Configuration:**
      Please create a `.env` file at the project's root and add the following environment variable to be able to login and signup:
     `NEXT_PUBLIC_API_URL=https://dewordle.onrender.com/api/v1`

## Definition of Done

1. User data is successfully stored using the Context API upon login.
2. The `/game` route correctly displays the logged-in user's username.
3. Appropriate error messages are shown when login fails, preserving the application's stability.
4. Code changes are well-documented and follow the project’s coding standards.

Let's make DeWordle even more user-friendly! 🚀

### PR DESCRIPTION
**Pull request by Nishantsingh11**
# Pull Request

## Description
This PR introduces changes to persist user data using the Context API and display the logged-in user's username on the /game route. After a successful sign-in, the user data is stored in the context and in localStorage, ensuring that the username (and other details) is accessible across components. This provides immediate feedback to users that they are logged in, enhancing the overall user experience.

## Related Issue

Closes #330

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)Update your CONTRIBUTING.md to reference the template

- [ ] Documentation update

- [ ] Code refactoring

- [ ] Performance improvement

- [ ] Test update

- [ ] Build/CI pipeline change

- [ ] Other (please describe):

## Checklist

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) document.

- [x] My code follows the code style of this project.

- [x] I have commented my code, particularly in hard-to-understand areas.

- [ ] I have made corresponding changes to the documentation.

- [x] My changes generate no new warnings.

- [x] I have added tests that prove my fix is effective or that my feature works.

- [ ] New and existing unit tests pass locally with my changes.

- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots/Recordings

https://github.com/user-attachments/assets/c8c197a5-f3a3-4552-bdb4-05dd973c9f10

## Additional Context

- The PR ensures that if no user is logged in, the Navbar defaults to showing a "Guest" message or similar prompt.

-The user data is read from localStorage on application load and then stored in Context via the AppProvider, ensuring centralized state management.

-All changes are in line with the DeWordle styling and coding guidelines.

## Testing Instructions
Testing Instructions
Login Process:

Navigate to the sign-in page and log in with valid credentials.

Verify that after login, the user data (username, etc.) is stored in localStorage.

Check that the Context is updated with the correct user data.

`/game` Route:

Navigate to the `/game` route.

Confirm that the Navbar displays "Hi [username]" where [username] is the logged-in user's name.

Error Handling:

Try logging in with invalid credentials and verify that appropriate error messages are displaye

### CODE REVIEW

File: frontend/app/hooks/useSignIn.js [hunk 1]
```diff
@@ -1,14 +1,29 @@
...
 
+
 export function useSignin() {
+
+  // const context = useContext(AppContext);
+
+  // if (!context) {
+  //   console.log('useSignin must be used within an AppProvider');
+  // }
+  // const { setUserData } = context || {};
```
Comment (Ibinola) [inline frontend/app/hooks/useSignIn.js:17]: please remove comments

File: frontend/app/hooks/useSignIn.js [hunk 2]
```diff
@@ -1,14 +1,29 @@
...
   return useMutation({
     mutationFn: (data) => API.post(`${URL}/sign-in`, data),
     onSuccess: (res) => {
-      localStorage.setItem('currentUser', res.data);
+      // setUserData(res.data[1]);
+      const userData = res.data[1];
+      localStorage.setItem('authToken', res.data[0].token);
+
+      localStorage.setItem('currentUser', JSON.stringify(userData));
+      console.log('Sign In Successfully', res);
```
Comment (Ibinola) [inline frontend/app/hooks/useSignIn.js:26]: remove `console.log`

File: frontend/components/Navbar.jsx [hunk 3]
```diff
@@ -22,7 +23,8 @@ const Navbar = () => {
   const dropdownRef = useRef(null);
   const profileButtonRef = useRef(null);
   const router = useRouter();
-
+  const { userData } = useContext(AppContext);
+  console.log('userData from navabr', userData);
```
Comment (Ibinola) [inline frontend/components/Navbar.jsx:27]: remove `console.log`

File: frontend/components/Navbar.jsx [hunk 4]
```diff
@@ -22,7 +23,8 @@ const Navbar = () => {
...
   const user = {
     name: "John Stones",
     email: "johnstones1@gmail.com",
```
Comment (Ibinola) [inline frontend/components/Navbar.jsx:30]: this can be deleted

**Review by Nishantsingh11 — COMMENTED** [review]
Hey, I've made some changes based on the review. Please take a look!

**Comment by Ibinola** [comment]
@Nishantsingh11 good work!

**Comment by Nishantsingh11** [comment]
Thank you very much
